services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: g3-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "VanshitaP@19"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
  g3_carrentalapplication.gateway:
    image: ${DOCKER_REGISTRY-}g3carrentalapplicationgateway
    build:
      context: .
      dockerfile: G3_CarRentalApplication.Gateway/Dockerfile

  g3_carrentalapplication.mvc:
    image: ${DOCKER_REGISTRY-}g3carrentalapplicationmvc
    build:
      context: .
      dockerfile: G3_CarRentalApplication.MVC/Dockerfile


  g3vehicleinventory.webapi:
    image: ${DOCKER_REGISTRY-}g3vehicleinventorywebapi
    build:
      context: .
      dockerfile: G3VehicleInventory.WebAPI/Dockerfile


  g3customerapi:
    image: ${DOCKER_REGISTRY-}g3customerapi
    build:
      context: .
      dockerfile: G3CustomerAPI/Dockerfile


  g3maintenanceapi:
    image: ${DOCKER_REGISTRY-}g3maintenanceapi
    build:
      context: .
      dockerfile: G3MaintenanceAPI/Dockerfile


  g3reservationapi:
    image: ${DOCKER_REGISTRY-}g3reservationapi
    build:
      context: .
      dockerfile: G3ReservationAPI/Dockerfile

volumes:
  sql_data:

